### ISSUE TITLE
Plan?

### ISSUE THREAD

**Issue by browniefed** [animatedjs/animated#1]
What's the plan? And how can I help?

**Comment by lelandrichardson** [comment]
@browniefed I've just committed an initial implementation.  The readme lays out some plans... a lot of this stuff I just went initially with what I think is best, and we should probably have a lot more discussion around.

After the inital implementation, I'm going to start making changes as PRs so we can discuss them before they're merged.

I'm going to put up a PR shortly regarding a way to implement arbitrary shapes that are complex animated values (ie, `AnimatedWithChildren`) which I think is an important topic for this library. 

I'm also going to try and get some documentation spun up, and the tests running along with CI.

**Comment by browniefed** [comment]
Cool, sounds good! I like the way things are looking so far.

**Comment by nvcken** [comment]
How is this vs https://github.com/chenglou/react-motion?

**Comment by browniefed** [comment]
@nvcken Animated works by manipulating the target directly(DOM, native world, anything) vs using `setState`. This allows for things to be performant but the way that Animated is developed allows for it to still work with `setState` being called mid-animation.

You can watch more about it here https://www.youtube.com/watch?v=xtqUJVqpKNo to see the technique that was developed and reasons behind it.

Once Animated matures react-motion may very well build upon it.

**Comment by amannn** [comment]
Just learned about this library in the recent React Conf talk from Ryan Florence. Looks very nice, I was actually hoping that Animated is going to be released for the web eventually.

I'm wondering about the status of the project. Ryan mentioned it's beta – is that true? Is it currently used somewhere in production or are there any important things missing currently? Or is there a general roadmap for this library? The README says that React Native will depend on this library at some point.

Thanks!
