### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by necolas** [animatedjs/animated#18]
Are changes here being upstreamed to RN, or are RN changes being copied here?

I'd like to depend on this package for react-native-web rather than manually tracking changes in RN. But it's not yet published to npm. If it were, we could be testing it out on web. The current target exports aren't really appropriate for RN for Web, as I'd want to hook it up to `View`, `Text`, etc.

**Comment by gre** [comment]
at the moment they are being copied in from RN, eventually we should have a npm package with RN depending on it.

**Comment by browniefed** [comment]
You could always `npm install animatedjs/animated`

**Comment by necolas** [comment]
> You could always npm install animatedjs/animated

I could but I have to transpile the source code out from node_modules.

**Comment by browniefed** [comment]
It happened! https://www.npmjs.com/package/animated
