### ISSUE TITLE
.__getValue() versus .getValue()

### ISSUE THREAD

**Issue by lelandrichardson** [animatedjs/animated#2]
I noticed this was changed to `.getValue()` in the interactive docs repo, but in RN right now it is `.__getValue()`.

@vjeux , I assume this was done as a precaution because having a synchronous getValue method would make it a lot harder to offload the animation loops to a separate thread.

This repo is currently using the `__getValue` version. Thought I'd open up a discussion to see if we'd want to change. If changing would mean we won't be able to get this lib as a dep for RN as well, I say we keep it undocumented and pseudo-private.

**Comment by vjeux** [comment]
We should not make it public. I'm not sure why I renamed it to getValue here, maybe I just got lazy :p

**Comment by lelandrichardson** [comment]
:+1:

**Comment by browniefed** [comment]
Yeah from my understanding it was to make it private since people (like me) were using it to get animated values synchronously which was frowned upon.
