### ISSUE TITLE
Broken with React 15.0.0

### ISSUE THREAD

**Issue by TheSisb** [animatedjs/animated#23]
CSSPropertyOperations' `setValueForStyles` now expects a `component` argument but animated is passing an instance object: https://github.com/animatedjs/animated/blob/9e509b53ebb57d02fb1695b7dc03a888a13dfa57/src/targets/react-dom.js#L37

**Comment by browniefed** [comment]
Ah thanks, will take a look at it later today when I get a second.

**Comment by TheSisb** [comment]
Actually I'm pretty sure you can get past this issue by omitting the component argument.  I believe it's only for debugging.

**Comment by browniefed** [comment]
Should be fixed now. Thanks for reporting.
