### ISSUE TITLE
Animate values inside a calc() expression

### ISSUE THREAD

**Issue by arcanis** [animatedjs/animated#29]
Is it possible to animate values inside calc expressions? For example, something like this:

```
width: calc(300px + ${progress} * (100% - 300px));
```

**Comment by sahrens** [comment]
You should use `interpolate`. There should be a bunch of documentation and examples if you search. If you can't get something in particular to work, let us know.

On Apr 26, 2016, at 2:30 AM, Maël Nison <notifications@github.com<mailto:notifications@github.com>> wrote:

Is it possible to animate values inside calc expressions? For example, something like this:

width: calc(300px + ${progress} \* (100% - 300px));

**Comment by arcanis** [comment]
I've successfully used `interpolate` to remap simple values from the `[0;1]` range to `[0.9;1.0]`, but I'm not sure how I can use it to remap arbitrary values in the middle of a string (as in the example above).

The reason I use a calc construct (instead of interpolating from X to Y and use that as a width) is that interpolate works fine if the property value only has to deal with a single unit, but not that much if there's more that two units involved (as in the example above, where both px and % are used in the same expression). Did I missed something?

**Comment by arcanis** [comment]
That might be a bad idea, but have you considered using tagged literals for this purpose? For example, the API could be as simple as this (`Animated.tpl` being the tag):

``` js
render() {
    let style = { width: Animated.tpl `calc(300px + ${progress} * (100% - 300px))` };
    return <Animated.div style={style}>Hello</Animated.div>
}
```

It would also fix the #31 issue in the process, since crafting the job of crafting the transform would be left to the user instead of the library (which is probably more performant anyway):

``` js
render() {
    let style = { transform: Animated.tpl `scaleX(${this.state.progress}) rotateX(${this.state.progress})` };
    return <Animated.div style={style}>Hello</Animated.div>
}
```

As final perk, it would also opens new CSS property to be animated (such as filters), background position, etc.

**Comment by sahrens** [comment]
Oh I see.  That does seem pretty interesting. What do you think, @vjeux?

**Comment by sahrens** [comment]
The API may need to be a bit more restrictive than that, but I like the concept.

**Comment by vjeux** [comment]
This should already be supported today. You can write the following:

``` js
width: this.progress.interpolate({
  inputRange: [0, 1],
  outputRange: [
    'calc(300px + 0 * (100% - 300px))',
    'calc(300px + 1 * (100% - 300px))',
  ]
})
```

Animated will extract all the numbers and interpolate them. Since the numbers are the same for 300, 100 and 300, it's just going to leave them as is but will make the transition between 0 and 1

**Comment by vjeux** [comment]
But, I really like your proposal where you can specify where each component is. Right now the solution above relies on extracting things that look like numbers from a string which is not ideal

**Comment by vjeux** [comment]
I'd be down to accept if you can implement it. I don't think it has much value inside of React Native since we are doing everything possible to avoid strings as value but for the web I can see the use case.

``` js
style={{
  width: Animated.template`calc(300px + ${progress} * (100% - 300px))`,
}}
```

**Comment by vjeux** [comment]
You can look at AnimatedTransform as a base to implement it: https://github.com/animatedjs/animated/blob/master/src/AnimatedTransform.js

**Comment by arcanis** [comment]
@vjeux Sure, I've just opened a PR with a tentative implementation

**Comment by souporserious** [comment]
Just wanted to say thank you for this 🙏 I was able to get some pretty cool animations working quickly with the template feature 🎉

**Comment by browniefed** [comment]
Sadly this is only supported on web :( need to port this back to native.
