### ISSUE TITLE
License, etc.

### ISSUE THREAD

**Issue by lelandrichardson** [animatedjs/animated#3]
When pulling this code from the RN repo, I left whatever licensing information was in the files. However, when I added package.json, I did not add any information for license or author. Additionally, there is currently no LICENSE file in the project root.

@vjeux, i figured you could fill this out yourself, or let me know what you want it to be?

Additionallly, should new files have a comment-based preamble similar to the RN repo?

Please advise.

Thanks.

**Comment by vjeux** [comment]
Can you add

https://github.com/facebook/react-native/blob/master/LICENSE
https://github.com/facebook/react-native/blob/master/PATENTS

and the fb header on all the files.

**Comment by lelandrichardson** [comment]
Will do. I'll copy the license to the package.json as well.
