### ISSUE TITLE
RequestIdle implementation

### ISSUE THREAD

**Issue by arcanis** [animatedjs/animated#30]
I noticed something in my application: if a redux action is processed while Animated is performing an animation, a quite noticeable lag occurs. I tried using `requestIdleCallback` to alleviate this issue, but unfortunately it doesn't have any effect - I can only guess it's because the animation is performed using Javascript.

I'm not sure if this repository is open to feature requests, but I feel like a requestIdle equivalent would be a nice improvement (to delay the Redux actions until the animations have finished).

**Comment by arcanis** [comment]
Until this feature is made available natively, or as a workaround if it isn't, here is [a gist](https://gist.github.com/arcanis/c07806cbb908050a9587e60a9e5e7ef0) that shows how to implement such a function in user-land. You can use this module as such:

``` js
// First we need to hook ourselves on top of the requestAnimationFrame used by Animated
Animated.inject.RequestAnimationFrame(fn => {
    requestIdle.increaseRefCount();
    global.requestAnimationFrame(() => {
        requestIdle.decreaseRefCount();
        fn();
    });
});

// Then all we have to do is to call requestIdle(), which will return a promise resolved as
// soon as the animations are finished
requestIdle().then(() => {
    store.dispatch(resourceSet(...));
});
```

**Comment by sahrens** [comment]
We also have InteractionManager which might be a more robust way to make sure your operation doesn't interrupt any animations.

On Apr 26, 2016, at 7:17 AM, Maël Nison <notifications@github.com<mailto:notifications@github.com>> wrote:

Until this feature is made available natively, or as a workaround if it isn't, here is a gisthttps://gist.github.com/arcanis/c07806cbb908050a9587e60a9e5e7ef0 that shows how to implement such a function in user-land. You can use this module as such:

// First we need to hook ourselves on top of the requestAnimationFrame used by Animated
Animated.inject.RequestAnimationFrame(fn => {
    requestIdle.increaseRefCount();
    global.requestAnimationFrame(() => {
        requestIdle.decreaseRefCount();
        fn();
    });
});

// Then all we have to do is to call requestIdle(), which will return a promise resolved when everything is still
requestIdle().then(() => {
    store.dispatch(resourceSet(...));
});

**Comment by arcanis** [comment]
Now I feel stupid! Thanks, it seems to be exactly what I was looking for ([doc](https://facebook.github.io/react-native/docs/interactionmanager.html), for anyone stumbling onto this issue).
