### ISSUE TITLE
`normalizeColor` is copy-pasted in several React projects

### ISSUE THREAD

**Issue by necolas** [animatedjs/animated#39]
`normalizeColor` is used in several places within `react-native` / `react-native-web`, and is also present in `animated`. To avoid redundancy I wonder if we could publish it as another separate package?

**Comment by lelandrichardson** [comment]
@necolas good call. I just published `normalize-css-color` under the `react-community` org. I will put up a PR for RN to depend on it, as well as react-primitives, and you are free to do so as well.

https://github.com/react-community/normalize-css-color

```
npm i normalize-css-color
```
