### ISSUE TITLE
CSSPropertyOperations breaks with react 15.4.0

### ISSUE THREAD

**Issue by jbovenschen** [animatedjs/animated#51]
Because some internal API's are moved with the react 15.4.0 release the CSSPropertyOperations module, within the react-dom target file is broken.

We can solve this by;
- Changing the import to require('react-dom/lib/CSSPropertyOperations').
- Clone the CSSPropertyOperations from the react repo.

Don't know what the most appropriate solution is.

**Comment by browniefed** [comment]
Change the import, happy to accept a PR if you send it

**Comment by jbovenschen** [comment]
I changed the import within #52, is it an issue that it would break older react 15.x releases or is it good for now?

**Comment by browniefed** [comment]
Can you bump to latest 15.4.2

**Comment by browniefed** [comment]
Actually it doesn't matter

**Comment by browniefed** [comment]
Published as 0.2.0
