### ISSUE TITLE
translateX and translateY don't work with React Web

### ISSUE THREAD

**Issue by miczed** [animatedjs/animated#58]
I am trying to build animated components which work both in React-Native an with React web.
So far everything worked fine. I could animate most of the properties. However translateX and translateY don't seem to work as far as I could tell:

This example doesn't work at all. No style attributes are set when I view the object in chrome's inspector.

```javascript
render() {
        let translateX = this.state.anim.x;
        let translateY = this.state.anim.y;
        let scale = this.state.anim.x.interpolate({ inputRange: [0, 100], outputRange: [0.3, 1], extrapolate: 'clamp' });
        const styles = {
            transform: [{translateX},{translateY},{scale}]
        };

        return(
            <Animated.div onMouseDown={this.handleClick} className="card" style={styles}><p>Click Me and I will move!</p></Animated.div>
        );
    }
```

However if I remove the transformX and Y properties, everything works fine:
```javascript
render() {
        let scale = this.state.anim.x.interpolate({ inputRange: [0, 100], outputRange: [0.3, 1], extrapolate: 'clamp' });
        const styles = {
            transform: [{scale}]
        };

        return(
            <Animated.div onMouseDown={this.handleClick} className="card" style={styles}><p>Click Me and I will move!</p></Animated.div>
        );
    }
```

- Maybe it's because on the web the unit "px" is missing? 
- How can I add an unit to an animated value? I tried the obvious solution of just doing `this.state.anim.x + "px"` but that doesn't seem to work either.

Any help would be highly appreciated. I've been stuck on this issue for quite some time now.

**Comment by soutar** [comment]
I think you might have meant translateX/Y instead of transformX/Y, so try changing that first. To add a suffix like 'px' or '%' you can use `Animated.template`. Try something like this:

```js
render() {
  const styles = {
    transform: Animated.template `
      translateX(${this.state.anim.x}px)
      translateY(${this.state.anim.y}px)
      scale(${this.state.anim.x.interpolate({
        inputRange: [0, 100],
        outputRange: [0.3, 1],
        extrapolate: 'clamp'
      })})
    `
  };

  return(
    <Animated.div onMouseDown={this.handleClick} className="card" style={styles}>
      <p>Click Me and I will move!</p>
    </Animated.div>
  );
}
```

You might also be able to use interpolate to add the suffix, but I'm not sure it supports px. It might look something like:
```js

this.state.anim.x.interpolate({
  inputRange: [0, 1],
  outputRange: ['0px', '1px']
})
```

**Comment by miczed** [comment]
Oh my bad, sorry for mixing transformX and translateX up. 

Thank you very much for your solution! It worked like a charm.

Is there a documentation for `Animated.template `somewhere?

**Comment by soutar** [comment]
No problem, I'm glad it worked. 👍 

`Animated.template` was introduced here in https://github.com/animatedjs/animated/pull/32 but I'm pretty sure it's not available in RN. You might want to explore the the `interpolate` solution if you need it to work cross-platform.

As for docs I don't think any exist other than discussion in #29.

**Comment by miczed** [comment]
Thanks for pointing that out, I'll try the `interpolate` solution as well.
