### ISSUE TITLE
Splitting up files

### ISSUE THREAD

**Issue by lelandrichardson** [animatedjs/animated#6]
I'm thinking about opening a PR moving each class in the `AnimatedImplementation` file into it's own file for better organization.

Any strong feelings against this?

**Comment by vjeux** [comment]
Yes please!

I put everything in one file when I was hacking on it. I refactored it probably 10 times before I got something that I was pleased with.

Now that the implementation is pretty solid, it's worth splitting up, this file has gotten huge over time.
