### ISSUE TITLE
React v16 Support

### ISSUE THREAD

**Issue by browniefed** [animatedjs/animated#63]
Currently we pull a file from core here https://github.com/animatedjs/animated/blob/master/src/targets/react-dom.js#L13

CSSPropertyOperations is what applies styles to our DOM elements. This will need to be fixed for the next version.

Haven't looked at what that's going to take yet

**Comment by paigecwilley** [comment]
I've noticed a number of styles getting applied to the Animated object, but not to the DOM elements. Could that be related to this issue?

**Comment by browniefed** [comment]
This is specifically for `react@next`.

The Web version of Animated only looks at the `style` object. It doesn't actually operate on any other property like the react-native version.
Mostly because with react-native there is the ability to call `setNativeProps` and we are updating a different system.

For the web we could check if the element we are operating on is a DOM element and scan the props for Animated values. It just currently doesn't do this.

**Comment by necolas** [comment]
FYI, I did this for react-native-web here: https://github.com/necolas/react-native-web/blob/c7686209cdeac808a0cf890d3bb60cdf4803c681/src/vendor/setValueForStyles/index.js

**Comment by julienvincent** [comment]
Any update on this?

**Comment by dariocravero** [comment]
@julienvincent you can use https://github.com/viewsdx/react-dom-animated in the meantime until support gets merged.

**Comment by caseybaggz** [comment]
Any new status regarding this? I tried using the temp package and still got the same result with using React v16 (web)

**Comment by browniefed** [comment]
This has now been released as v0.2.1
