### ISSUE TITLE
Still an active library?

### ISSUE THREAD

**Issue by ghost** [animatedjs/animated#73]
Forgive the impertinent question. I've just stumbled onto this library, and it looks really impressive, but it hasn't seen a release since early 2017. Is this still in active development? I'd like to roll it into the app I'm working on, but obviously wouldn't want to use it if it's dormant.

Thanks! (and sorry)

**Comment by browniefed** [comment]
It's not actively developed here, but is in React Native. There is nothing inherently wrong with it. Hopefully we can get the gap bridged and take all the improvements from react native and bring them here

**Comment by drcmda** [comment]
@browniefed will React 16 be supported? I saw in the other thread that someone's already solved the issue in react-native-web but here last time i tried it failed still. With Fiber getting closer and closer i'm a little nervous because almost all of my projects use this library. 😇

**Comment by ghost** [comment]
Yeah, I guess that's my question as well. Can we expect this (really nice) library to be supported for the foreseeable future? Would I be safe in using it for a production site? "No" would be a perfectly acceptable, though mildly depressing, answer.

Happy fourth!

**Comment by browniefed** [comment]
It would work, and people use it in production. Will it continue to work into the future: yes. There may need to be some work done to make it work with React 16 as I haven't tested it.

Would I personally use it in production, probably not.

**Comment by ghost** [comment]
Okay, so you guys still see this as an experimental library that one day may be production-ready in your view, but is not currently at that stage, and you have no fixed timetable for if or when that might happen. All totally fine--I just want to make sure I understand your intent.

**Comment by browniefed** [comment]
For the web that is an accurate statement.
For React Native it's very stable, just no one is really currently actively working on the web version besides when I occasionally get a few moments to attempt a PR/migrate some code which isn't often. This library isn't a priority for me.

**Comment by ghost** [comment]
Understood, and thanks. I think, given how well it seems to work, you'd have a lot of fans if you or a compatriot decided to focus on the web version at some point. React + animations on the web is still a tough nut to crack.
