### ISSUE TITLE
Status of animated?

### ISSUE THREAD

**Issue by mikeaustin** [animatedjs/animated#76]
Hi. This project sounds like the perfect solution to React animation, but I'm curious of the status of this project? Development and discussion seems to have stopped the last few months? Ultimately, I'm curious how others are creating React Native/Web compatible animations-specifically transitions. I've been following react-native-web for a bit, and there is active development. Anyone know of other projects or other idea related to this?

**Comment by loanlaux** [comment]
+1

And it doesn't seem to work with React 16.

**Comment by browniefed** [comment]
Works with v16 now. This isn't necessarily in any sort of active development but it does work.
It could definitely be optimized to work with React 16 and it's priority queue to be much better suited for the web.
