### ISSUE TITLE
React 16 doesn't allow private API access

### ISSUE THREAD

**Issue by loganpowell** [animatedjs/animated#86]
I'm sorry if I'm missing something, but when I update to React 16+ I get an error:

```
./node_modules/animated/lib/targets/react-dom.js
Module not found: Can't resolve 'react-dom/lib/CSSPropertyOperations'
```

After some Google'ing, I found [a tweet](https://twitter.com/dan_abramov/status/798926305030877184) from Dan Abramov saying:

> Just a reminder: importing from react/lib/* or react-dom/lib/* was never supported, and will break more in the future. Don’t do this.

Is there a better way to use the `animated.js` library than what I'm doing here:

https://github.com/loganpowell/router-transition-animation/blob/master/src/AnimatedRoutes.js#L4

**Comment by browniefed** [comment]
You must have installed an older version. The latest doesn't reach into the React code base anymore.

**Comment by loganpowell** [comment]
@browniefed Ah! I used 0.2.0. I will update to 0.2.1 :)

traced: https://github.com/stereobooster/react-snap/issues/116#issuecomment-357539756

**Comment by loganpowell** [comment]
Sorry, how should I import the library now? I.e., instead of

```js
import * as Animated from 'animated/lib/targets/react-dom';
```

**Comment by browniefed** [comment]
Should work exactly the same.

**Comment by loganpowell** [comment]
I'm probably doing something wrong! Thank you for your time :)

**Comment by loganpowell** [comment]
Yup! I had a duplication of React when I upgraded and found a related issue:

https://github.com/JedWatson/react-select/issues/606#issuecomment-216768095

Reinstalled everything and now works perfectly!
