### ISSUE TITLE
Proposal: Add an `isAnimated(val)` existential method

### ISSUE THREAD

**Issue by lelandrichardson** [animatedjs/animated#9]
``` js
var Animated = require('animated');
var anim = new Animated.Value(123);
var interp = anim.interpolate({ ... });
Animated.isAnimated(anim) // true
Animated.isAnimated(interp) // true
Animated.isAnimated(123) // false
```

This would be a good API to provide people for detecting whether or not a given value is an animated value or not. This could be used, for example, to produce PropTypes helpers for the library.

**Comment by gre** [comment]
Big +1 for this

Le dim. 28 févr. 2016 17:47, Leland Richardson notifications@github.com a
écrit :

**Comment by browniefed** [comment]
Yeah I think this is great, although it'll have to pair nicely with however we decide to move forward with custom animated values. Whether that is just extending `AnimatedWithChildren` or otherwise.

**Comment by lelandrichardson** [comment]
@browniefed i'm working on a proposal for that right now.  Either way, it should work fine.  The test would basically just check: `value instanceof Animated`, but `Animated` itself wouldn't be an exported class. However we create new animated shapes, they would inevitably inherit from `Animated`

**Comment by browniefed** [comment]
Tis what I figured :+1:

**Comment by vjeux** [comment]
Really smart! I've been struggling to figure out how to encode that. Make it happen :)

**Comment by gre** [comment]
@lelandrichardson if Animated/AnimatedWithChildren is not exposed, how can a third party library implement his own Animated? Will the library expose ways to create an Animated class?
My use-case is animated over uniforms for gl-react: https://github.com/ProjectSeptemberInc/gl-react/blob/master/src/AnimatedData.js#L42

**Comment by lelandrichardson** [comment]
@gre can you weigh in on this PR? I'm curious if this would solve your use case. https://github.com/animatedjs/animated/pull/12
