### ISSUE TITLE
New instance of Animated Value not reflected in Component on mount

### ISSUE THREAD

**Issue by zachgibson** [animatedjs/animated#90]
I’m creating a new instance of `Animated.Value` and passing 0 to use in a scale transform, but the component doesn’t initially have a scale of 0. Opacity works like this, but transforms don’t. Maybe I’m missing something? Here’s a [CodeSandbox](https://codesandbox.io/s/o4m48x0456).

Code:
```JSX
import React from "react";
import { render } from "react-dom";
import * as Animated from "animated/lib/targets/react-dom";

const anim = new Animated.Value(0);

const App = () => (
  <Animated.div
    style={{
      transform: [{ scale: anim }],
      width: 80,
      height: 80,
      backgroundColor: "red"
    }}
  />
);

render(<App />, document.getElementById("root"));
```
Screenshot (red square should be scale(0)): 
![image](https://user-images.githubusercontent.com/10658888/36170193-54bee5fc-10c4-11e8-8ac0-ae32975d497d.png)

**Comment by browniefed** [comment]
Yep.
https://github.com/animatedjs/animated/pull/91

I'll merge it later after a review, thanks for catching that.

**Comment by zachgibson** [comment]
Whoa thanks for fixing this so quickly. You da man.

**Comment by browniefed** [comment]
v0.2.2 is out with this fix. Hopefully I didn't break anything :)
