### ISSUE TITLE
Is it possible to set delay to animation?

### ISSUE THREAD

**Issue by 01Kuzma** [animatedjs/animated#94]
Is it possible to set delay to animation before transform?

**Comment by browniefed** [comment]
Use Animated.sequence with an Animated.delay before your animation executes, or just delay the animation before you call start.

**Comment by 01Kuzma** [comment]
Could you please post a sample?

**Comment by browniefed** [comment]
```
Animated.sequence([
Animated.delay(500),
Animated.timing()
]).start()
```

This can all be found from simple googling and reading of docs.
